In [ ]:
# Parameters

CampañasxPeriodo=18
UltimaCampañaRolling=202818
CampañaInicioRolling=202610
Carpeta=r'C:\Users\williamtorres\OneDrive - CETCO S.A\SAP IBP\Rolling forecast\Corrida 09.07.2025\SAP\Resultado CORP\103'

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [3]:
df_Meta = pd.read_csv(rf'{Carpeta}\df_Meta.csv')
df_Meta.head()

   2026         2027         2028
0   0.0  2374340.634  2381049.138
1   0.0  2457564.803  2464508.443
2   0.0  2505557.470  2512636.706
3   0.0  2406665.756  2413465.589
4   0.0  2461450.087  2468404.704

In [4]:
año_base = datetime.today().year
vector_Meta = (
    df_Meta[f"{año_base+1}"].tolist()
    + df_Meta[f"{año_base+2}"].tolist()
    + df_Meta[f"{año_base+3}"].tolist()
)
vector_Meta

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2533629.523,
 2328485.877,
 2434008.827,
 2381544.682,
 2327237.09,
 2340943.503,
 2590154.491,
 2423298.112,
 2648275.186,
 2374340.634,
 2457564.803,
 2505557.47,
 2406665.756,
 2461450.087,
 2544717.74,
 2397228.621,
 2372123.939,
 2474002.934,
 2543601.302,
 2337772.24,
 2443647.758,
 2391008.323,
 2336519.281,
 2350271.489,
 2600315.129,
 2431393.235,
 2657121.992,
 2381049.138,
 2464508.443,
 2512636.706,
 2413465.589,
 2468404.704,
 2551907.616,
 2404001.791,
 2378826.18,
 2480993.017,
 2550788.024,
 2344377.426,
 2450552.078,
 2397763.918,
 2343120.927,
 2356911.99,
 2607662.087,
 2438262.932,
 2664629.449]

In [5]:
df = pd.read_csv(rf'{Carpeta}\df_Linea.csv')

In [6]:
df.head()

,Tipo,SAP,Categoría,UU,Grupo art.,SM,CampaniaDescontinuacion,Crecimiento X,Crecimiento X+1,Crecimiento X+2,Crecimiento X+3,Descripción SAP,Período,Ce.,JERARQUIA,EDL,CDP,novoApp,campaña
0,Supply Original,200118771,c.Cuidado Personal,2084,103,AC,0.0,-0.011057,0.007899,0.003341,0.002825,ES AGU SH AROMA RELAJANTE 1L,2025 C10,CO03,SHAMPOO,-,B. Colombia,NaN,202510
1,Supply Original,200118771,c.Cuidado Personal,1355,103,AC,0.0,-0.011057,0.007899,0.003341,0.002825,ES AGU SH AROMA RELAJANTE 1L,2025 C11,CO03,SHAMPOO,-,B. Colombia,NaN,202511
2,Supply Original,200118771,c.Cuidado Personal,4806,103,AC,0.0,-0.011057,0.007899,0.003341,0.002825,ES AGU SH AROMA RELAJANTE 1L,2025 C12,CO03,SHAMPOO,-,B. Colombia,NaN,202512
3,Supply Original,200118771,c.Cuidado Personal,2842,103,AC,0.0,-0.011057,0.007899,0.003341,0.002825,ES AGU SH AROMA RELAJANTE 1L,2025 C13,CO03,SHAMPOO,-,B. Colombia,NaN,202513
4,Supply Original,200118771,c.Cuidado Personal,3696,103,AC,0.0,-0.011057,0.007899,0.003341,0.002825,ES AGU SH AROMA RELAJANTE 1L,2025 C14,CO03,SHAMPOO,-,B. Colombia,NaN,202514

In [7]:
# Crear tabla dinámica
tabla_pivot = pd.pivot_table(
    df,
    index=["Ce.", "Grupo art.", "Crecimiento X+2", "Crecimiento X+3", "CampaniaDescontinuacion", "SAP"], # filas
    columns="campaña",   # columnas
    values="UU",  # la métrica que quieres sumar/promediar
    aggfunc="sum",       # puede ser sum, mean, count, etc.
    fill_value=0
)

In [8]:
tabla_pivot

campaña                                                                            202510  \
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     163
                                                                        200078924     140
                                                                        200082688     251
                                                                        200085860     133
                                                                        200095177     139
...                                                                                   ...
SV13 103        0.003341        0.002825        202607.0                200107823     128
                                                                        200107827     200
                                                                        200110112     110
                                                                        200110113     113
                                                                        200115279    3902

campaña                                                                            202511  \
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     435
                                                                        200078924     297
                                                                        200082688     460
                                                                        200085860     238
                                                                        200095177     754
...                                                                                   ...
SV13 103        0.003341        0.002825        202607.0                200107823      61
                                                                        200107827     134
                                                                        200110112      70
                                                                        200110113      40
                                                                        200115279    3592

campaña                                                                            202512  \
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     275
                                                                        200078924     257
                                                                        200082688     369
                                                                        200085860     186
                                                                        200095177     751
...                                                                                   ...
SV13 103        0.003341        0.002825        202607.0                200107823      93
                                                                        200107827     134
                                                                        200110112     122
                                                                        200110113      52
                                                                        200115279    8233

campaña                                                                            202513  \
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     414
                                                                        200078924     359
                                                                        200082688     430
                                                                        200085860     251
                                                                        200095177     799
...                                                                                   ...
SV13 103        0.003341        0.002825        202607.0                200107823     102
                                                                        200107827     172
                                                                        200110112      64
                                                                        200110113      53
                                                                        200115279    9635

campaña                                                                            202514  \
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     325
                                                                        200078924     355
                                                                        200082688     320
                                                                        200085860     165
                                                                        200095177     830
...                                                                                   ...
SV13 103        0.003341        0.002825        202607.0                200107823     104
                                                                        200107827     177
                                                                        200110112     107
                                                                        200110113      77
                                                                        200115279   10263

campaña                                                                            202515  \
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     252
                                                                        200078924     208
                                                                        200082688     237
                                                                        200085860     111
                                                                        200095177     864
...                                                                                   ...
SV13 103        0.003341        0.002825        202607.0                200107823      79
                                                                        200107827     109
                                                                        200110112     162
                                                                        200110113      67
                                                                        200115279    9344

campaña                                                                            202516  \
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     264
                                                                        200078924     472
                                                                        200082688     307
                                                                        200085860     152
                                                                        200095177     713
...                                                                                   ...
SV13 103        0.003341        0.002825        202607.0                200107823      91
                                                                        200107827     192
                                                                        200110112     106
                                                                        200110113     103
                                                                        200115279   12346

campaña                                                                            202517  \
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     355
                                                                        200078924     371
                                                                        200082688     443
                                                                        200085860     258
                                                                        200095177     746
...                                                                                   ...
SV13 103        0.003341        0.002825        202607.0                200107823      74
                                                                        200107827      97
                                                                        200110112      52
                                                                        200110113      37
                                                                        200115279   13447

campaña                                                                            202518  \
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     332
                                                                        200078924     535
                                                                        200082688     342
                                                                        200085860     215
                                                                        200095177     807
...                                                                                   ...
SV13 103        0.003341        0.002825        202607.0                200107823     216
                                                                        200107827     104
                                                                        200110112     118
                                                                        200110113     107
                                                                        200115279    5723

campaña                                                                            202601  \
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     356
                                                                        200078924     282
                                                                        200082688     429
                                                                        200085860     301
                                                                        200095177     772
...                                                                                   ...
SV13 103        0.003341        0.002825        202607.0                200107823     216
                                                                        200107827     136
                                                                        200110112     120
                                                                        200110113     100
                                                                        200115279    8818

campaña                                                                            202602  \
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     241
                                                                        200078924     282
                                                                        200082688     325
                                                                        200085860     198
                                                                        200095177     784
...                                                                                   ...
SV13 103        0.003341        0.002825        202607.0                200107823     230
                                                                        200107827     141
                                                                        200110112     146
                                                                        200110113     114
                                                                        200115279    8431

campaña                                                                            202603  \
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     330
                                                                        200078924     282
                                                                        200082688     401
                                                                        200085860     283
                                                                        200095177     771
...                                                                                   ...
SV13 103        0.003341        0.002825        202607.0                200107823     216
                                                                        200107827     133
                                                                        200110112     119
                                                                        200110113     100
                                                                        200115279    9160

campaña                                                                            202604  \
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     331
                                                                        200078924     282
                                                                        200082688     408
                                                                        200085860     285
                                                                        200095177     764
...                                                                                   ...
SV13 103        0.003341        0.002825        202607.0                200107823     248
                                                                        200107827     139
                                                                        200110112     143
                                                                        200110113     114
                                                                        200115279    8702

campaña                                                                            202605  \
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     323
                                                                        200078924     282
                                                                        200082688     383
                                                                        200085860     200
                                                                        200095177     799
...                                                                                   ...
SV13 103        0.003341        0.002825        202607.0                200107823     216
                                                                        200107827     138
                                                                        200110112     116
                                                                        200110113     115
                                                                        200115279    9168

campaña                                                                            202606  \
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     243
                                                                        200078924     272
                                                                        200082688     301
                                                                        200085860     155
                                                                        200095177     725
...                                                                                   ...
SV13 103        0.003341        0.002825        202607.0                200107823     214
                                                                        200107827     149
                                                                        200110112     109
                                                                        200110113     120
                                                                        200115279    8565

campaña                                                                            202607  \
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     354
                                                                        200078924     353
                                                                        200082688     410
                                                                        200085860     269
                                                                        200095177     954
...                                                                                   ...
SV13 103        0.003341        0.002825        202607.0                200107823     228
                                                                        200107827     162
                                                                        200110112     138
                                                                        200110113     137
                                                                        200115279    8369

campaña                                                                            202608  \
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     354
                                                                        200078924     353
                                                                        200082688     477
                                                                        200085860     269
                                                                        200095177     924
...                                                                                   ...
SV13 103        0.003341        0.002825        202607.0                200107823       0
                                                                        200107827       0
                                                                        200110112       0
                                                                        200110113       0
                                                                        200115279       0

campaña                                                                            202609
Ce.  Grupo art. Crecimiento X+2 Crecimiento X+3 CampaniaDescontinuacion SAP
BO03 103        0.003341        0.002825        0.0                     200064341     354

In [9]:
def generar_campañas(inicio, fin):
    """
    Genera lista de campañas desde 'inicio' hasta 'fin'
    considerando que cada año solo llega hasta 18,
    luego pasa al siguiente año con 01.
    """
    campañas = []
    año = int(str(inicio)[:4])
    periodo = int(str(inicio)[-2:])
    año_fin = int(str(fin)[:4])
    periodo_fin = int(str(fin)[-2:])

    while (año < año_fin) or (año == año_fin and periodo <= periodo_fin):
        campañas.append(int(f"{año}{periodo:02d}"))
        periodo += 1
        if periodo > CampañasxPeriodo:   # al pasar de 18 reinicia
            periodo = 1
            año += 1
    return campañas

In [10]:
# Generar campañas desde la mínima hasta 202818
campaña_min = int(df["campaña"].min())
campañas_completas = generar_campañas(campaña_min, UltimaCampañaRolling)

# Reindexar columnas
tabla_pivot = tabla_pivot.reindex(columns=campañas_completas, fill_value=0)

# Tabla plana opcional
tabla_pivot = tabla_pivot.reset_index()

In [11]:
tabla_pivot.head()

campaña,Ce.,Grupo art.,Crecimiento X+2,Crecimiento X+3,CampaniaDescontinuacion,SAP,202510,202511,202512,202513,...,202809,202810,202811,202812,202813,202814,202815,202816,202817,202818
0,BO03,103,0.003341,0.002825,0.0,200064341,163,435,275,414,...,0,0,0,0,0,0,0,0,0,0
1,BO03,103,0.003341,0.002825,0.0,200078924,140,297,257,359,...,0,0,0,0,0,0,0,0,0,0
2,BO03,103,0.003341,0.002825,0.0,200082688,251,460,369,430,...,0,0,0,0,0,0,0,0,0,0
3,BO03,103,0.003341,0.002825,0.0,200085860,133,238,186,251,...,0,0,0,0,0,0,0,0,0,0
4,BO03,103,0.003341,0.002825,0.0,200095177,139,754,751,799,...,0,0,0,0,0,0,0,0,0,0

In [12]:
# Buscar la última campaña con valor > 0 en cada fila
tabla_pivot["ÚltimoCampañaLinea"] = tabla_pivot.apply(
    lambda row: max([col for col in tabla_pivot.columns if isinstance(col, int) and row[col] > 0], default=None),
    axis=1
)

In [13]:
tabla_pivot

campaña,Ce.,Grupo art.,Crecimiento X+2,Crecimiento X+3,CampaniaDescontinuacion,SAP,202510,202511,202512,202513,...,202810,202811,202812,202813,202814,202815,202816,202817,202818,ÚltimoCampañaLinea
0,BO03,103,0.003341,0.002825,0.0,200064341,163,435,275,414,...,0,0,0,0,0,0,0,0,0,202609
1,BO03,103,0.003341,0.002825,0.0,200078924,140,297,257,359,...,0,0,0,0,0,0,0,0,0,202609
2,BO03,103,0.003341,0.002825,0.0,200082688,251,460,369,430,...,0,0,0,0,0,0,0,0,0,202609
3,BO03,103,0.003341,0.002825,0.0,200085860,133,238,186,251,...,0,0,0,0,0,0,0,0,0,202609
4,BO03,103,0.003341,0.002825,0.0,200095177,139,754,751,799,...,0,0,0,0,0,0,0,0,0,202609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,SV13,103,0.003341,0.002825,202607.0,200107823,128,61,93,102,...,0,0,0,0,0,0,0,0,0,202607
706,SV13,103,0.003341,0.002825,202607.0,200107827,200,134,134,172,...,0,0,0,0,0,0,0,0,0,202607
707,SV13,103,0.003341,0.002825,202607.0,200110112,110,70,122,64,...,0,0,0,0,0,0,0,0,0,202607
708,SV13,103,0.003341,0.002825,202607.0,200110113,113,40,52,53,...,0,0,0,0,0,0,0,0,0,202607
709,SV13,103,0.003341,0.002825,202607.0,200115279,3902,3592,8233,9635,...,0,0,0,0,0,0,0,0,0,202607

In [14]:
def siguiente_campaña(camp):
    """Dada una campaña tipo 202615, devuelve la siguiente (202616 o 202701 si era 18)."""
    camp = int(camp)
    año = camp // 100
    num = camp % 100
    if num == 18:
        año += 1
        num = 1
    else:
        num += 1
    return int(f"{año}{num:02d}")


for idx_row, row in tabla_pivot.iterrows():
    ultima = row["ÚltimoCampañaLinea"]
    descontinuacion = row["CampaniaDescontinuacion"]

    if pd.isna(descontinuacion) or descontinuacion == 0:
        descontinuacion = UltimaCampañaRolling
    
    if pd.isna(ultima):
        continue
    
    # siguiente campaña al último estimado
    siguiente = siguiente_campaña(ultima)
    
    # inicio: mayor entre 202612 y esa siguiente
    inicio = max(CampañaInicioRolling, siguiente)

    # si no está en campañas_completas (por ejemplo 202619), saltamos al próximo válido
    while inicio not in campañas_completas and inicio < max(campañas_completas):
        inicio = siguiente_campaña(inicio)

    if inicio not in campañas_completas:
        continue  # nada que proyectar

    start_index = campañas_completas.index(inicio)

    # proyectar desde inicio hasta el final del horizonte
    for j in range(start_index, len(campañas_completas)):
        camp = campañas_completas[j]
        if camp > descontinuacion:  # 🚫 parar si pasa la campaña de descontinuación
            break
        prev_3 = campañas_completas[start_index-1:start_index]   # las 3 campañas anteriores en la lista
        tabla_pivot.at[idx_row, camp] = row[prev_3].mean()

In [15]:
tabla_pivot

campaña,Ce.,Grupo art.,Crecimiento X+2,Crecimiento X+3,CampaniaDescontinuacion,SAP,202510,202511,202512,202513,...,202810,202811,202812,202813,202814,202815,202816,202817,202818,ÚltimoCampañaLinea
0,BO03,103,0.003341,0.002825,0.0,200064341,163,435,275,414,...,354,354,354,354,354,354,354,354,354,202609
1,BO03,103,0.003341,0.002825,0.0,200078924,140,297,257,359,...,353,353,353,353,353,353,353,353,353,202609
2,BO03,103,0.003341,0.002825,0.0,200082688,251,460,369,430,...,457,457,457,457,457,457,457,457,457,202609
3,BO03,103,0.003341,0.002825,0.0,200085860,133,238,186,251,...,269,269,269,269,269,269,269,269,269,202609
4,BO03,103,0.003341,0.002825,0.0,200095177,139,754,751,799,...,981,981,981,981,981,981,981,981,981,202609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,SV13,103,0.003341,0.002825,202607.0,200107823,128,61,93,102,...,0,0,0,0,0,0,0,0,0,202607
706,SV13,103,0.003341,0.002825,202607.0,200107827,200,134,134,172,...,0,0,0,0,0,0,0,0,0,202607
707,SV13,103,0.003341,0.002825,202607.0,200110112,110,70,122,64,...,0,0,0,0,0,0,0,0,0,202607
708,SV13,103,0.003341,0.002825,202607.0,200110113,113,40,52,53,...,0,0,0,0,0,0,0,0,0,202607
709,SV13,103,0.003341,0.002825,202607.0,200115279,3902,3592,8233,9635,...,0,0,0,0,0,0,0,0,0,202607

In [16]:
# Aseguramos que los nombres de columnas sean string
tabla=tabla_pivot
tabla = tabla.rename(columns=str)

# Identificar columnas que son campañas (números de 6 dígitos) y mayores a 202610
cols_a_eliminar = [col for col in tabla.columns if col.isdigit() and int(col) <CampañaInicioRolling ]

# Eliminar esas columnas
tabla = tabla.drop(columns=cols_a_eliminar)

In [17]:
tabla

campaña,Ce.,Grupo art.,Crecimiento X+2,Crecimiento X+3,CampaniaDescontinuacion,SAP,202610,202611,202612,202613,...,202810,202811,202812,202813,202814,202815,202816,202817,202818,ÚltimoCampañaLinea
0,BO03,103,0.003341,0.002825,0.0,200064341,354,354,354,354,...,354,354,354,354,354,354,354,354,354,202609
1,BO03,103,0.003341,0.002825,0.0,200078924,353,353,353,353,...,353,353,353,353,353,353,353,353,353,202609
2,BO03,103,0.003341,0.002825,0.0,200082688,457,457,457,457,...,457,457,457,457,457,457,457,457,457,202609
3,BO03,103,0.003341,0.002825,0.0,200085860,269,269,269,269,...,269,269,269,269,269,269,269,269,269,202609
4,BO03,103,0.003341,0.002825,0.0,200095177,981,981,981,981,...,981,981,981,981,981,981,981,981,981,202609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,SV13,103,0.003341,0.002825,202607.0,200107823,0,0,0,0,...,0,0,0,0,0,0,0,0,0,202607
706,SV13,103,0.003341,0.002825,202607.0,200107827,0,0,0,0,...,0,0,0,0,0,0,0,0,0,202607
707,SV13,103,0.003341,0.002825,202607.0,200110112,0,0,0,0,...,0,0,0,0,0,0,0,0,0,202607
708,SV13,103,0.003341,0.002825,202607.0,200110113,0,0,0,0,...,0,0,0,0,0,0,0,0,0,202607
709,SV13,103,0.003341,0.002825,202607.0,200115279,0,0,0,0,...,0,0,0,0,0,0,0,0,0,202607

In [18]:
vector_sin_ceros = [x for x in vector_Meta if x != 0]

In [19]:
# Aseguramos que los nombres de columnas sean string
tabla.columns = tabla.columns.map(str)

# Filtrar las que son campañas (6 dígitos)
cols_campañas = [col for col in tabla.columns if col.isdigit() and len(col) == 6]

# Contar
n_campañas = len(cols_campañas)

print("Número de campañas:", n_campañas)

Número de campañas: 45

In [20]:
len(vector_sin_ceros)

45

In [21]:
# 3. Escalar cada columna al valor meta
for i, col in enumerate(cols_campañas):
    suma_actual = tabla[col].sum()
    meta = vector_sin_ceros[i]
    if suma_actual > 0:  # evitar división por cero
        factor = meta / suma_actual
        tabla[col] = tabla[col] * factor
    else:
        tabla[col] = 0  # si toda la columna es cero, dejarla en cero

In [22]:
# Calcular suma por columna
tabla[cols_campañas] = tabla[cols_campañas].round(0).astype(int)
suma_columnas = tabla[cols_campañas].sum()

In [23]:
# Comparar con las metas
verificacion = pd.DataFrame({
    "Campaña": cols_campañas,
    "Suma_calculada": suma_columnas.values,
    "Meta": vector_sin_ceros
})
print(verificacion)

   Campaña  Suma_calculada         Meta
0   202610         2533641  2533629.523
1   202611         2328484  2328485.877
2   202612         2434007  2434008.827
3   202613         2381554  2381544.682
4   202614         2327240  2327237.090
5   202615         2340947  2340943.503
6   202616         2590156  2590154.491
7   202617         2423287  2423298.112
8   202618         2648273  2648275.186
9   202701         2374345  2374340.634
10  202702         2457563  2457564.803
11  202703         2505558  2505557.470
12  202704         2406671  2406665.756
13  202705         2461461  2461450.087
14  202706         2544707  2544717.740
15  202707         2397234  2397228.621
16  202708         2372121  2372123.939
17  202709         2474007  2474002.934
18  202710         2543596  2543601.302
19  202711         2337766  2337772.240
20  202712         2443649  2443647.758
21  202713         2391022  2391008.323
22  202714         2336511  2336519.281
23  202715         2350276  2350271.489
24  202716         2600315  2600315.129
25  202717         2431394  2431393.235
26  202718         2657127  2657121.992
27  202801         2381061  2381049.138
28  202802         2464511  2464508.443
29  202803         2512628  2512636.706
30  202804         2413465  2413465.589
31  202805         2468393  2468404.704
32  202806         2551898  2551907.616
33  202807         2404000  2404001.791
34  202808         2378833  2378826.180
35  202809         2480997  2480993.017
36  202810         2550787  2550788.024
37  202811         2344377  2344377.426
38  202812         2450554  2450552.078
39  202813         2397752  2397763.918
40  202814         2343126  2343120.927
41  202815         2356918  2356911.990
42  202816         2607673  2607662.087
43  202817         2438267  2438262.932
44  202818         2664635  2664629.449

In [24]:
tabla.to_excel(
    rf"{Carpeta}\ProyecionLínea.xlsx", 
    sheet_name="Proyeccion", 
    index=False
)

In [25]:
tabla= tabla.drop(columns=['Grupo art.','Crecimiento X+2',
            'Crecimiento X+3',      'CampaniaDescontinuacion', 'ÚltimoCampañaLinea'])
tabla.head()

campaña,Ce.,SAP,202610,202611,202612,202613,202614,202615,202616,202617,...,202809,202810,202811,202812,202813,202814,202815,202816,202817,202818
0,BO03,200064341,353,325,340,332,325,327,361,338,...,346,356,327,342,335,327,329,364,340,372
1,BO03,200078924,352,324,339,331,324,326,360,337,...,345,355,326,341,334,326,328,363,339,371
2,BO03,200082688,456,419,438,429,419,422,467,436,...,447,459,422,441,432,422,425,470,439,480
3,BO03,200085860,269,247,258,252,247,248,275,257,...,263,270,249,260,254,248,250,276,259,283
4,BO03,200095177,980,900,941,921,900,905,1001,937,...,959,986,906,947,927,906,911,1008,943,1030

In [26]:
tabla.columns

Index(['Ce.', 'SAP', '202610', '202611', '202612', '202613', '202614',
       '202615', '202616', '202617', '202618', '202701', '202702', '202703',
       '202704', '202705', '202706', '202707', '202708', '202709', '202710',
       '202711', '202712', '202713', '202714', '202715', '202716', '202717',
       '202718', '202801', '202802', '202803', '202804', '202805', '202806',
       '202807', '202808', '202809', '202810', '202811', '202812', '202813',
       '202814', '202815', '202816', '202817', '202818'],
      dtype='object', name='campaña')

In [27]:
tabla = tabla.melt(
    id_vars=["Ce.", 'SAP'],  
    var_name="campaña",
    value_name="Estimado"
)

In [28]:
tabla.head()

    Ce.        SAP campaña  Estimado
0  BO03  200064341  202610       353
1  BO03  200078924  202610       352
2  BO03  200082688  202610       456
3  BO03  200085860  202610       269
4  BO03  200095177  202610       980

In [29]:
tabla_larga=tabla
tabla_larga=tabla_larga[tabla_larga["Estimado"]>0]
tabla_larga["TO"] = "'000"
tabla_larga["Estimado"] = tabla_larga["Estimado"].astype(int)
tabla_larga["SAP"] = tabla_larga["SAP"].astype(int)
tabla_larga.columns=["Ce.",'Cod', 'Campaña', 'Estimado', "TO" ]
tabla_larga.head()

C:\Users\williamtorres\AppData\Local\Temp\ipykernel_34368\618254320.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabla_larga["TO"] = "'000"
C:\Users\williamtorres\AppData\Local\Temp\ipykernel_34368\618254320.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabla_larga["Estimado"] = tabla_larga["Estimado"].astype(int)
C:\Users\williamtorres\AppData\Local\Temp\ipykernel_34368\618254320.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabla_larga["SAP"] = tabla_larga["SAP"].astype(int)

    Ce.        Cod Campaña  Estimado    TO
0  BO03  200064341  202610       353  '000
1  BO03  200078924  202610       352  '000
2  BO03  200082688  202610       456  '000
3  BO03  200085860  202610       269  '000
4  BO03  200095177  202610       980  '000

In [30]:
tabla_larga=tabla_larga[["Ce.", 'Campaña', 'Cod', "TO", 'Estimado']]

In [31]:
tabla_larga.to_excel(
    rf"{Carpeta}\CargaLínea.xlsx", 
    sheet_name="Proyeccion", 
    index=False
)